### ISSUE TITLE
Dependencies check

### ISSUE THREAD

**Issue by zygimantas** [aspnet/DnxTools#13]
There should be a dnu command to check if the latest versions of dependencies are configured in project.json.

Something like: "dnu check update" which checks all dependencies and updates the project.json or prints the list or new releases inside console if "update" command is not provided.

**Comment by Eilon** [comment]
@zygimantas can you log this in https://github.com/aspnet/dnx/? This repo is for some build tools and not DNU. Sorry for the confusion!
