### ISSUE TITLE
The NuGet package verifiers should be upgraded to dotnet

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/DnxTools#14]
The new build script doesn't include dnx anymore so the package verifier will not work.

cc @ajaybhargavb

**Comment by Eilon** [comment]
@ajaybhargavb might need to discuss with @victorhurdugaci to figure out what to do here.

**Comment by ajaybhargavb** [comment]
5a6ab6fe0bce09352ae5882f4c8ab01c4f22ff77
