### ISSUE TITLE
Need to figure out a way to specify the DNX version to run the tool

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/DnxTools#2]
Ref: https://github.com/aspnet/Universe/pull/256#discussion_r36361970
cc' @Eilon

**Comment by Eilon** [comment]
Changing the title to reflect the new dotnet-cli world. Ultimately this project needs to always use a consistent dotnet-cli, regardless of what other dotnet-cli's someone might have on their machine.

**Comment by pranavkm** [comment]
As of https://github.com/aspnet/DnxTools/commit/5a6ab6fe0bce09352ae5882f4c8ab01c4f22ff77 - we produce a NET451 exe. This doesn't require a host so this requirement should go away.
