### ISSUE TITLE
Need a centralized way to specify rules.

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/DnxTools#20]
It is a pain to update all repos whenever we add a new verification rule. Instead we need to have a central location where we can specify rule sets which can then be added to all repos.

cc' @Eilon @pranavkm

**Comment by ajaybhargavb** [comment]
The easiest way to do this would be to add more composite rules where each of them would run multiple rules. Eg: `SigningVerificationCompositeRule` will run both `AuthenticodeSigningRule` and `PowerShellScriptIsSignedRule`. This way the existing scenarios will also work.

**Comment by Eilon** [comment]
Would these be rulesets or actual new classes that run N sub-rules? I'd prefer to have this done "in config" as opposed to having to author actual composite rules.

**Comment by ajaybhargavb** [comment]
Yes. They will be new classes. I suggested it because it will be the easiest thing to do and there is no need to touch any of the existing code. What do you think is the downside to doing this?

**Comment by Eilon** [comment]
We would have to update the package verifier itself to define new combos or to add/remove rules from our listings.

I think I'm fine with this for now because it sounds fairly easy, but I don't think it's the cleanest approach.

**Comment by ajaybhargavb** [comment]
1466e8e2403b2fa88ba2dac4f125e4cb91fd02e6
