### ISSUE TITLE
Split RequiredPackageMetadataRule into two

### ISSUE THREAD

**Issue by Eilon** [aspnet/DnxTools#26]
1. One rule that we can run within each repo to check for stuff we specify in project.json, such as title, summary, tags
2. Another rule that has all the stuff we update in dnx.msbuild in Coherence-Signed

Then immediately enable rule (2) in Coherence-Signed.

We can't yet enable rule (1) because we're still missing some package metadata.

**Comment by ajaybhargavb** [comment]
012969e2537a33ecf2c0cc20d3b705417df5585a
