### ISSUE TITLE
Check the commit hash during verification

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/DnxTools#34]
@ajaybhargavb can the nuget verifier check properties on the assemblies inside? Recently I made a change to embed the commit hash as an `AssemblyMetadataAttribute` and it would be nice to check it for the packages that we ship

**Comment by ajaybhargavb** [comment]
Yes. For example take a look at `AssemblyHasCompanyAttributeRule`

**Comment by victorhurdugaci** [comment]
Just a note on this one: the source packages (packages that don't have binaries in them) don't have commit hashes. The rule needs to take that into account and verify that there's no source file in the package (`*.generated.cs`) that contains that attribute.

**Comment by Eilon** [comment]
Hmm could we have a convention in the rule that ignores `*.Sources` packages? I don't like the idea of using `*.generated.cs` as a flag because there could be other files that match that pattern.

**Comment by ryanbrandenburg** [comment]
What's the best way to test this?

**Comment by Eilon** [comment]
I would ignore `.Sources` packages and check everything else.

**Comment by victorhurdugaci** [comment]
Unzip the nupkg and check that the assemblies inside have the attribute set and its value matches the format of a commit hash. It would be too hard to verify that the actual value is the right commit.

**Comment by victorhurdugaci** [comment]
Oh, you mean the sources packages or how to test the attribute? :confused:

**Comment by ajaybhargavb** [comment]
Ignoring `.Sources` should be easy. We have access to the package id in the rule.

**Comment by Eilon** [comment]
Yeah of course we can't check that the hash is actually correct - we just want to verify existence.

**Comment by ryanbrandenburg** [comment]
I was asking what the best way to set this up to test that my changes is since there's no tests.

**Comment by ajaybhargavb** [comment]
I would just test this manually by running this rule on packages with and without the commit hash.

**Comment by Eilon** [comment]
Yeah run it on some packages built on a recent Coherence-Signed, and it should pass (include both regular and .Sources packages). Then run it on older Coherence-Signed packages and it should fail.
