### ISSUE TITLE
Split packages should generate a big project.json

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/DnxTools#38]
Generate a list of all packages.

The split packages tool generates 3 list of packages: ship, no ship, and ext as `project.json` files. It would be nice if it could generate 1 gigantic file with all the packages from a build...

I think @davidfowl needs the full list.

cc @javiercn

**Comment by Eilon** [comment]
Type `dir`?

**Comment by javiercn** [comment]
What's the purpose of having a single project.json file? I'm fine with whatever change you want to make as long as is additive, meaning you can change it to generate a big project.json file too if you want, but keep generating the project.json files per folder as we use/will use those project.json files for installers and other things.

**Comment by Eilon** [comment]
I'm rather dubious of needing a big project.json because why would anyone care about anything but what we ship?

@davidfowl speak up, or we'll close this :smile:

**Comment by Eilon** [comment]
Closing for now. @davidfowl let me know if you still need this.
