### ISSUE TITLE
Add check for company/copyright/etc. attributes

### ISSUE THREAD

**Issue by Eilon** [aspnet/DnxTools#4]

**Comment by Eilon** [comment]
We should discuss this one before starting it to ensure we are looking at the right set of attributes.

**Comment by ajaybhargavb** [comment]
List of attributes to look for,
- AssemblyCopyright
- AssemblyCompany
- AssemblyConfiguration
- AssemblyDescription
- AssemblyDefaultAlias
- AssemblyTitle
- AssemblyProduct
- AssemblyTrademark

**Comment by Eilon** [comment]
`2.5 - Needs to be done` :trollface:

**Comment by ajaybhargavb** [comment]
Oops.
