### ISSUE TITLE
SplitPackages needs to fail with a summary of all failures

### ISSUE THREAD

**Issue by pranavkm** [aspnet/DnxTools#40]
Right now it looks like it fails at the first package that is missing or new. It makes it very difficult to work with when a bunch of csv changes have to be made.

**Comment by Eilon** [comment]
@javiercn can you take a look at this once your other RC2 items are in good shape?

**Comment by javiercn** [comment]
Just remove --warningsaserrors from the arguments passed to the tool and that will switch to producing warnings for all the mismatched packages.

Sent from Outlook
________________________________

**Comment by Eilon** [comment]
Ah ok that's a good temporary workaround.

**Comment by pranavkm** [comment]
Yup - that's what I did for now.
