### ISSUE TITLE
SigningVerificationCompositeRule does not perform strong name verification

### ISSUE THREAD

**Issue by pranavkm** [aspnet/DnxTools#53]
We should add it as a secondary check to individual repo check.

**Comment by ajaybhargavb** [comment]
Fixed in https://github.com/aspnet/DnxTools/pull/58

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/DnxTools/commit/0158152e961711caf2b1ee21ea9ff233a2a3830c
