### ISSUE TITLE
SplitPackages doesn't handle packages that don't target net451

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DnxTools#89]
For example, [Microsoft.EntityFrameworkCore.Tools.DotNet](https://github.com/aspnet/EntityFramework/blob/9cc12d67a3c1442ea979f1775d8a1322e524219b/src/Tools.DotNet/project.nuspec). This causes restore errors and test failures on Coherence

```
Package Microsoft.EntityFrameworkCore.Tools.DotNet 1.0.0-preview3-21860 is not compatible with net451
```

cc @javiercn

**Comment by natemcmaster** [comment]
cc @pranavkm

**Comment by Eilon** [comment]
@muratg @javiercn @pranavkm let's talk about this on Monday when everyone is in.

**Comment by Eilon** [comment]
(We have some not-too-crazy ideas about how to fix this.)

**Comment by pranavkm** [comment]
I also filed a poorly titled bug in Coherence about this - https://github.com/aspnet/Coherence/issues/120

**Comment by javiercn** [comment]
https://github.com/aspnet/DnxTools/commit/0da7ded2c9a5368db95e078d4326f4426a473766
